# To enable set SPRING_PROFILES_ACTIVE=dev

debug: true
server:
  port: ${PORT:8080}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: INFO

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-iwyuw5rnqqzmi8i3.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: https://sip-api-endpoint

# datasource config
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/sip-backend-db
    username: application
    password: application
    driver-class-name: org.postgresql.Driver

# flyway migration config
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/sip-backend-db
    user: ddl-user
    password: ddl-user