debug: true
server:
  port: ${PORT:3010}

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-iwyuw5rnqqzmi8i3.us.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: https://sip-api-endpoint
